### ISSUE TITLE
Alertmanager was unable to connect to the alertmanager2es service

### ISSUE THREAD

**Issue by yuanyiran** [webdevops/alertmanager2es#1]
Hello, I'm sorry to disturb you. I'm using the alertmanager2es service in kubernetes. After successful startup, the alertmanager service also configures the webhook address. However, an error is reported in the log and cannot connect to the alertmanager2es service. Do you have any reference solutions?

![image](https://user-images.githubusercontent.com/64528937/91699051-46043200-eba6-11ea-83ef-06f97274767a.png)

![image](https://user-images.githubusercontent.com/64528937/91699084-574d3e80-eba6-11ea-9333-b99742130975.png)

![image](https://user-images.githubusercontent.com/64528937/91699129-68964b00-eba6-11ea-860f-68c41e085309.png)

![image](https://user-images.githubusercontent.com/64528937/91699144-6fbd5900-eba6-11ea-8fda-145ccc665a79.png)

**Comment by mblaschke** [comment]
Can you try it with `20.8.1`?
Can you post your kubernetes manifest?

**Comment by mblaschke** [comment]
closing, no feedback
